# FOHM AMR Pipeline - Conda Environment
# Create with: conda env create -f environment.yml
# Activate with: conda activate fohm-amr-pipeline

name: fohm-amr-pipeline
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  # Core system
  - python=3.11
  - pip>=23.0

  # Workflow management
  - nextflow>=23.04.0

  # Bioinformatics tools
  - fastqc>=0.11.9
  - multiqc>=1.19
  - trimmomatic>=0.39
  - spades>=3.15.0
  - flye>=2.9.0
  - rgi>=6.0.0  # Resistance Gene Identifier for AMR

  # Container technologies
  - docker-py>=6.0.0
  - singularity>=3.8.0

  # Data processing
  - pandas>=1.5.0
  - numpy>=1.21.0
  - scipy>=1.9.0
  - matplotlib>=3.5.0
  - seaborn>=0.11.0

  # Quality control and reporting
  - jinja2>=3.0.0
  - pyyaml>=6.0
  - click>=8.0.0
  - coloredlogs>=15.0
  - markdown>=3.3.0
  - lxml>=4.6.0
  - pillow>=8.0.0

  # File handling
  - openpyxl>=3.0.9
  - xlsxwriter>=3.0.0

  # Development tools
  - black>=22.0.0
  - flake8>=4.0.0
  - pytest>=7.0.0

  # Documentation
  - sphinx>=4.0.0
  - sphinx-rtd-theme>=1.0.0

  # Additional pip packages not available in conda
  - pip:
    - spectra>=0.0.11
    - simplejson>=3.17.0