# FOHM AMR Pipeline - Minimal Working Environment
# Create with: conda env create -f environment.yml
# Activate with: conda activate fohm-amr-pipeline

# For conda environment.yml, add:
# - pyarrow=12.0.0
# - pandas=1.5.3
name: fohm-amr-pipeline
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  # Core system
  - python=3.9
  - pip>=23.0

  # Workflow management
  - nextflow>=23.04.0

  # Quality Control Tools (essential working versions)
  - fastqc=0.11.9
  - multiqc=1.19
  - quast=5.2.0

  # Read Processing
  - trimmomatic=0.39

  # Assembly Tools (stable versions)
  - spades=3.15.0
  - flye=2.9.0

  # AMR Analysis (ABRicate - reliable alternative to RGI)
  - abricate=1.0.1

  # Essential utilities (stable versions)
  - samtools=1.15
  # Skip bcftools and blast for now to avoid conflicts

  # Data processing libraries (minimal set)
  - pandas=1.5.3
  - numpy=1.24.3
  - matplotlib=3.7.1
  - pyarrow=20.0.0

  # Report generation essentials
  - jinja2=3.1.2
  - pyyaml=6.0
  - click=8.1.3
  - mummer=3.23 

  # Development tools
  - black=23.3.0

  # File handling
  - openpyxl=3.1.2

  # Container build (IO version - lighter)
  - Docker= 27.5.1 

  # Additional tools via pip (avoiding conda conflicts)
  - pip:
    - plotly>=5.0.0
    - seaborn>=0.12.0
    - spectra>=0.0.11
    - simplejson>=3.17.0
    - coloredlogs>=15.0
    - markdown>=3.3.0
    - xlsxwriter>=3.0.0